runtime: nodejs18

instance_class: F1

handlers:
  - url: /
    static_files: dist/my-angular-app/index.html
    upload: dist/my-angular-app/index.html

  - url: /(.*\.js)$  # Match JavaScript files
    static_files: dist/my-angular-app/\1
    upload: dist/my-angular-app/(.*\.js)$

  - url: /(.*\.css)$  # Match CSS files
    static_files: dist/my-angular-app/\1
    upload: dist/my-angular-app/(.*\.css)$

  - url: /(.*\.png)$  # Match PNG files
    static_files: dist/my-angular-app/\1
    upload: dist/my-angular-app/(.*\.png)$

  - url: /(.*\.jpg)$  # Match JPG files
    static_files: dist/my-angular-app/\1
    upload: dist/my-angular-app/(.*\.jpg)$

  - url: /(.*\.ico)$  # Match ICO files
    static_files: dist/my-angular-app/\1
    upload: dist/my-angular-app/(.*\.ico)$
