name: Deploy to Google App Engine

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: ./my-angular-app/
        run: npm install

      - name: Lint and test
        working-directory: ./my-angular-app/
        run: |
          npm run lint
          npm test 

      - name: Build Angular app
        working-directory: ./my-angular-app/
        run: npm run build

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          version: '482.0.0'

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy to App Engine
        run: |
          gcloud app deploy --quiet ./my-angular-app/app.yaml --project ${{ secrets.GCP_PROJECT_ID }} --promote
